# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailmenus', '0021_auto_20170106_2352'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('lampstands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='tshirtpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='tshirtpage',
            name='page_ptr',
        ),
        migrations.RenameField(
            model_name='churchpage',
            old_name='address',
            new_name='meeting_address',
        ),
        migrations.RemoveField(
            model_name='churchpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='churchpage',
            name='locality_fax_number',
        ),
        migrations.RemoveField(
            model_name='churchpage',
            name='meeting_info',
        ),
        migrations.AlterField(
            model_name='churchpage',
            name='last_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TshirtPage',
        ),
    ]
