# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lampstandsrendition',
            name='filter',
        ),
    ]
