# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0002_auto_20170216_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageclient',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepageclient',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepageclient',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homepageclient',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blog_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='clients_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='work_title',
        ),
        migrations.DeleteModel(
            name='HomePageClient',
        ),
    ]
