# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0002_auto_20170322_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardpage',
            old_name='streamfield',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='beliefspage',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='beliefspage',
            name='letterdropcap',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='middle_break',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='quote',
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
