# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0003_auto_20170223_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author_left',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='marketing_only',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
