# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0004_auto_20170223_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='from_area',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
