# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 17:36
from __future__ import unicode_literals

from django.db import migrations
import lampstands.core.models
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0006_auto_20170328_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beliefspage',
            name='letterdropcap',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='letterdropcap',
        ),
        migrations.AlterField(
            model_name='beliefspage',
            name='streamfield',
            field=wagtail.fields.StreamField((('indexpreview', wagtail.blocks.TextBlock(max_length=300)), ('wholestory', wagtail.blocks.StreamBlock((('h2', wagtail.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', lampstands.core.models.ImageFormatChoiceBlock()), ('caption', wagtail.blocks.CharBlock()), ('attribution', wagtail.blocks.CharBlock(required=False))), label='Aligned image')), ('wide_image', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()),), label='Wide image')), ('bustout', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.RichTextBlock())))), ('pullquote', wagtail.blocks.StructBlock((('quote', wagtail.blocks.CharBlock(classname='quote title')), ('attribution', wagtail.blocks.CharBlock())))), ('raw_html', wagtail.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='code')))))), help_text='Use Raw HTML option if dropcaps etc. are needed to customize look'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='streamfield',
            field=wagtail.fields.StreamField((('indexpreview', wagtail.blocks.TextBlock(max_length=400)), ('wholestory', wagtail.blocks.StreamBlock((('h2', wagtail.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', lampstands.core.models.ImageFormatChoiceBlock()), ('caption', wagtail.blocks.CharBlock()), ('attribution', wagtail.blocks.CharBlock(required=False))), label='Aligned image')), ('wide_image', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()),), label='Wide image')), ('bustout', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.RichTextBlock())))), ('pullquote', wagtail.blocks.StructBlock((('quote', wagtail.blocks.CharBlock(classname='quote title')), ('attribution', wagtail.blocks.CharBlock())))), ('raw_html', wagtail.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='code'))))), ('stats', wagtail.blocks.StructBlock(())), ('wideimage', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()),))), ('bustout', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.RichTextBlock())))), ('pullimgquote', wagtail.blocks.StructBlock((('quote', wagtail.blocks.CharBlock()), ('attribution', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))))), ('pullquote', wagtail.blocks.StructBlock((('quote', wagtail.blocks.CharBlock(classname='quote title')), ('attribution', wagtail.blocks.CharBlock())))), ('photogrid', wagtail.blocks.StructBlock((('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())),))), ('img', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', lampstands.core.models.ImageFormatChoiceBlock()), ('caption', wagtail.blocks.CharBlock()), ('attribution', wagtail.blocks.CharBlock(required=False))))), ('imgchoice', lampstands.core.models.ImageFormatChoiceBlock())), help_text='Use Raw HTML option if dropcaps etc. are needed to customize look'),
        ),
    ]
