# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0007_auto_20170227_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagetagselect',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_page_tag_select', to='lampstands.BlogPageTagList'),
        ),
    ]
