# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailmenus', '0021_auto_20170106_2352'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('lampstands', '0008_auto_20170330_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketinglandingpage',
            name='hero_video_poster_image',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpagefeatureditem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpagefeatureditem',
            name='related_page',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpageheaderrelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpageheaderrelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpageheaderrelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpageintrorelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpageintrorelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpageintrorelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpagepageclients',
            name='image',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpagepageclients',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpagepageclients',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='marketinglandingpagepageclients',
            name='page',
        ),
        migrations.RemoveField(
            model_name='turnkeyaccreditations',
            name='image',
        ),
        migrations.RemoveField(
            model_name='turnkeyaccreditations',
            name='page',
        ),
        migrations.DeleteModel(
            name='TurnkeyApplication',
        ),
        migrations.RemoveField(
            model_name='turnkeypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='turnkeypageeventsmanaged',
            name='image',
        ),
        migrations.RemoveField(
            model_name='turnkeypageeventsmanaged',
            name='page',
        ),
        migrations.RemoveField(
            model_name='turnkeypagequote',
            name='page',
        ),
        migrations.DeleteModel(
            name='MarketingLandingPage',
        ),
        migrations.DeleteModel(
            name='MarketingLandingPageFeaturedItem',
        ),
        migrations.DeleteModel(
            name='MarketingLandingPageHeaderRelatedLink',
        ),
        migrations.DeleteModel(
            name='MarketingLandingPageIntroRelatedLink',
        ),
        migrations.DeleteModel(
            name='MarketingLandingPagePageClients',
        ),
        migrations.DeleteModel(
            name='TurnkeyAccreditations',
        ),
        migrations.DeleteModel(
            name='TurnkeyPage',
        ),
        migrations.DeleteModel(
            name='TurnkeyPageEventsManaged',
        ),
        migrations.DeleteModel(
            name='TurnkeyPageQuote',
        ),
    ]
