# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailmenus', '0021_auto_20170106_2352'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('lampstands', '0009_auto_20170401_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontentblock',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontentblock',
            name='page',
        ),
        migrations.RemoveField(
            model_name='aboutpageoffice',
            name='page',
        ),
        migrations.RemoveField(
            model_name='aboutpagerelatedlinkbutton',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='aboutpagerelatedlinkbutton',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='aboutpagerelatedlinkbutton',
            name='page',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='AboutPageContentBlock',
        ),
        migrations.DeleteModel(
            name='AboutPageOffice',
        ),
        migrations.DeleteModel(
            name='AboutPageRelatedLinkButton',
        ),
    ]
