# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0009_auto_20170228_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='information_bar_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonies_tag_line',
            field=models.TextField(blank=True),
        ),
    ]
