# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import lampstands.core.models
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0013_auto_20170406_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='question',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='streamfield',
            field=wagtail.fields.StreamField((('answer', wagtail.blocks.StreamBlock((('h2', wagtail.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', lampstands.core.models.ImageFormatChoiceBlock()), ('caption', wagtail.blocks.CharBlock()), ('attribution', wagtail.blocks.CharBlock(required=False))), label='Aligned image')), ('wide_image', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()),), label='Wide image')), ('bustout', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.RichTextBlock())))), ('pullquote', wagtail.blocks.StructBlock((('quote', wagtail.blocks.CharBlock(classname='quote title')), ('attribution', wagtail.blocks.CharBlock())))), ('raw_html', wagtail.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='code'))))),), help_text='Question and answer are to appear in same block'),
        ),
    ]
