# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailmenus', '0021_auto_20170106_2352'),
        ('lampstands', '0014_auto_20170302_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='jobindexpagejob',
            name='page',
        ),
        migrations.RemoveField(
            model_name='reasontojoin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reasontojoin',
            name='page',
        ),
        migrations.DeleteModel(
            name='JobIndexPage',
        ),
        migrations.DeleteModel(
            name='JobIndexPageJob',
        ),
        migrations.DeleteModel(
            name='ReasonToJoin',
        ),
    ]
