# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 05:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('lampstands', '0015_auto_20170302_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ChurchPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('locality_name', models.CharField(max_length=255)),
                ('locality_state_or_province', models.CharField(blank=True, max_length=255)),
                ('locality_country', django_countries.fields.CountryField(max_length=2)),
                ('short_intro', models.CharField(blank=True, help_text='A short summary of when the locality started meeting', max_length=255)),
                ('mail_address', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('locality_phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('locality_fax_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('locality_email', models.EmailField(max_length=254)),
                ('locality_web', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('meeting_info', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('last_update', models.DateField(null=True)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lampstands.LampstandsImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
