# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0015_auto_20170406_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypage',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
