# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 19:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0016_churchindexpage_churchpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchindexpage',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='churchpage',
            name='locality_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='churchpage',
            name='locality_web',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
