# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0017_aboutpage_aboutpagecontentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypage',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
