# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0018_auto_20170406_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='google_key_js',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_url_js',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
