# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0019_churchindexpagerelatedlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchpage',
            old_name='mail_address',
            new_name='address',
        ),
    ]
