# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0020_auto_20170411_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchpage',
            name='locality_city',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
