# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0021_churchpage_locality_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchpage',
            name='locality_city',
        ),
    ]
