# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0021_auto_20170320_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchpage',
            old_name='address',
            new_name='latlng',
        ),
    ]
