# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0023_auto_20170320_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchpage',
            name='address',
        ),
        migrations.AddField(
            model_name='churchpage',
            name='mailaddr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
