# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0023_auto_20170320_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchpage',
            name='address',
        ),
    ]
