# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 17:32
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0024_auto_20170321_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchpage',
            old_name='mailaddr',
            new_name='address',
        ),
        migrations.AddField(
            model_name='churchpage',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
