# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 07:57
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0024_remove_churchpage_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchpage',
            name='address',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
