# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:32
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0025_auto_20170321_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchpage',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
