# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0025_churchpage_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchpage',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
