# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0027_auto_20170428_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchpage',
            old_name='position',
            new_name='location',
        ),
    ]
