# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0028_auto_20170502_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchpage',
            old_name='location',
            new_name='position',
        ),
    ]
