# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0031_auto_20170504_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchpage',
            name='locality_web',
            field=models.TextField(blank=True, default='Unavailable', help_text="Please type: 'http://' in the front of the URL"),
        ),
    ]
