# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0032_auto_20170504_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchpage',
            name='locality_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='churchpage',
            name='locality_web',
            field=models.TextField(help_text="Please type: 'http://' in the front of the URL", null=True),
        ),
    ]
