# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0033_auto_20170505_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchpage',
            name='locality_email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='churchpage',
            name='locality_web',
            field=models.TextField(blank=True, default=None, help_text="Please type: 'http://' in the front of the URL"),
            preserve_default=False,
        ),
    ]
