# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampstands', '0034_auto_20170505_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchpage',
            name='locality_phone_number',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
